#############################################################################
# Makefile for building: XoPro1.app/Contents/MacOS/XoPro1
# Generated by qmake (3.1) (Qt 5.13.2)
# Project:  ../../XoPro1.pro
# Template: app
# Command: /Users/macbook/Qt/5.13.2/ios/bin/qmake -o XoPro1.xcodeproj/project.pbxproj ../../XoPro1.pro -spec macx-xcode CONFIG+=release CONFIG+=iphoneos CONFIG+=device CONFIG+=qtquickcompiler QMAKE_MAC_XCODE_SETTINGS+=qteam qteam.name=DEVELOPMENT_TEAM qteam.value=6Q32B3V4PN
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Users/macbook/Qt/5.13.2/ios/bin/qmake
XoPro1.xcodeproj/project.pbxproj: ../../XoPro1.pro /Users/macbook/Qt/5.13.2/ios/mkspecs/macx-ios-clang/qmake.conf /Users/macbook/Qt/5.13.2/ios/mkspecs/features/spec_pre.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/qdevice.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/device_config.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/common/unix.conf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/common/mac.conf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/common/uikit.conf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/common/ios.conf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/common/sanitize.conf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/common/gcc-base.conf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/common/gcc-base-mac.conf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/common/clang.conf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/common/clang-mac.conf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/common/uikit/clang.conf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/common/uikit/qmake.conf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/qconfig.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3drender.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_core.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_core_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_gui.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_help.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_help_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_location.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_location_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_macextras.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_network.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_network_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_nfc.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_opengl.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_positioning.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qml.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quick.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_repparser.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_scxml.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_sensors.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_sql.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_svg.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_testlib.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_uitools.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_websockets.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_webview.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_widgets.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_xml.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_darwingamepad.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qgif.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qicns.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qico.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qios.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmacheif.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtga.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_scene2d.pri \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/qt_functions.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/qt_config.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/macx-ios-clang/qmake.conf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/macx-xcode/qmake.conf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/spec_post.prf \
		../../../.qmake.stash \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/exclusive_builds.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/sdk.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/sdk.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/toolchain.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/toolchain.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/default_pre.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/default_pre.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/default_pre.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/resolve_config.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/resolve_config.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/default_post.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/default_post.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/default_post.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/objective_c.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/resources.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/qtquickcompiler.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/mac.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/bitcode.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/warn_on.prf \
		/Users/macbook/Qt/5.13.2/ios/plugins/platforms/libqios.prl \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/qt.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/qt.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/gc_binaries.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/moc.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/unix/opengl.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uic.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/unix/thread.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/qmake_use.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/file_copies.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/rez.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/asset_catalogs.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/testcase_targets.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/testcase_targets.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/exceptions.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/yacc.prf \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/features/lex.prf \
		../../XoPro1.pro \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		/Users/macbook/Qt/5.13.2/ios/mkspecs/macx-ios-clang/LaunchScreen.xib \
		../../MyFile.qrc \
		/Users/macbook/Qt/5.13.2/ios/lib/libQt5FontDatabaseSupport.prl \
		/Users/macbook/Qt/5.13.2/ios/lib/libqtfreetype.prl \
		/Users/macbook/Qt/5.13.2/ios/lib/libQt5GraphicsSupport.prl \
		/Users/macbook/Qt/5.13.2/ios/lib/libQt5ClipboardSupport.prl \
		/Users/macbook/Qt/5.13.2/ios/lib/libQt5Gui.prl \
		/Users/macbook/Qt/5.13.2/ios/lib/libqtlibpng.prl \
		/Users/macbook/Qt/5.13.2/ios/lib/libqtharfbuzz.prl \
		/Users/macbook/Qt/5.13.2/ios/lib/libQt5Core.prl \
		/Users/macbook/Qt/5.13.2/ios/lib/libqtpcre2.prl \
		/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqgif.prl \
		/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqicns.prl \
		/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqico.prl \
		/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqjpeg.prl \
		/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqmacheif.prl \
		/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqmacjp2.prl \
		/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqtga.prl \
		/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqtiff.prl \
		/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqwbmp.prl \
		/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqwebp.prl \
		/Users/macbook/Qt/5.13.2/ios/lib/libQt5Widgets.prl
	$(QMAKE) -o XoPro1.xcodeproj/project.pbxproj ../../XoPro1.pro -spec macx-xcode CONFIG+=release CONFIG+=iphoneos CONFIG+=device CONFIG+=qtquickcompiler QMAKE_MAC_XCODE_SETTINGS+=qteam qteam.name=DEVELOPMENT_TEAM qteam.value=6Q32B3V4PN
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/spec_pre.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/qdevice.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/device_config.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/common/unix.conf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/common/mac.conf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/common/uikit.conf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/common/ios.conf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/common/sanitize.conf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/common/gcc-base.conf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/common/gcc-base-mac.conf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/common/clang.conf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/common/clang-mac.conf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/common/uikit/clang.conf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/common/uikit/qmake.conf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/qconfig.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3danimation.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dcore.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dextras.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dinput.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquick.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3drender.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_concurrent.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_core.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_core_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_gamepad.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_gui.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_gui_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_help.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_help_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_location.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_location_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_macextras.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_multimedia.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_network.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_network_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_nfc.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_opengl.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_positioning.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qml.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qml_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qmltest.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quick.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quick_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_repparser.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_scxml.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_sensors.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_sql.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_sql_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_svg.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_svg_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_testlib.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_uitools.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_webchannel.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_websockets.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_webview.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_webview_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_widgets.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_xml.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_xml_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_lib_zlib_private.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_darwingamepad.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qgif.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qicns.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qico.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qios.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmacheif.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qminimal.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qsvg.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtga.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtiff.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_qwebp.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/modules/qt_plugin_scene2d.pri:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/qt_functions.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/qt_config.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/macx-ios-clang/qmake.conf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/macx-xcode/qmake.conf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/spec_post.prf:
../../../.qmake.stash:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/exclusive_builds.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/sdk.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/sdk.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/toolchain.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/toolchain.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/default_pre.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/default_pre.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/default_pre.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/resolve_config.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/resolve_config.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/default_post.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/default_post.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/default_post.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/macx-ios-clang/features/default_post.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/objective_c.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/resources.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/qtquickcompiler.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/mac.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/bitcode.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/warn_on.prf:
/Users/macbook/Qt/5.13.2/ios/plugins/platforms/libqios.prl:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/qt.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/qt.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/gc_binaries.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/moc.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/unix/opengl.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uic.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/unix/thread.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/qmake_use.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/file_copies.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/rez.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/mac/asset_catalogs.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/testcase_targets.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/uikit/testcase_targets.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/exceptions.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/yacc.prf:
/Users/macbook/Qt/5.13.2/ios/mkspecs/features/lex.prf:
../../XoPro1.pro:
/Users/macbook/Qt/5.13.2/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
/Users/macbook/Qt/5.13.2/ios/mkspecs/macx-ios-clang/LaunchScreen.xib:
../../MyFile.qrc:
/Users/macbook/Qt/5.13.2/ios/lib/libQt5FontDatabaseSupport.prl:
/Users/macbook/Qt/5.13.2/ios/lib/libqtfreetype.prl:
/Users/macbook/Qt/5.13.2/ios/lib/libQt5GraphicsSupport.prl:
/Users/macbook/Qt/5.13.2/ios/lib/libQt5ClipboardSupport.prl:
/Users/macbook/Qt/5.13.2/ios/lib/libQt5Gui.prl:
/Users/macbook/Qt/5.13.2/ios/lib/libqtlibpng.prl:
/Users/macbook/Qt/5.13.2/ios/lib/libqtharfbuzz.prl:
/Users/macbook/Qt/5.13.2/ios/lib/libQt5Core.prl:
/Users/macbook/Qt/5.13.2/ios/lib/libqtpcre2.prl:
/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqgif.prl:
/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqicns.prl:
/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqico.prl:
/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqjpeg.prl:
/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqmacheif.prl:
/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqmacjp2.prl:
/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqtga.prl:
/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqtiff.prl:
/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqwbmp.prl:
/Users/macbook/Qt/5.13.2/ios/plugins/imageformats/libqwebp.prl:
/Users/macbook/Qt/5.13.2/ios/lib/libQt5Widgets.prl:
qmake: FORCE
	@$(QMAKE) -o XoPro1.xcodeproj/project.pbxproj ../../XoPro1.pro -spec macx-xcode CONFIG+=release CONFIG+=iphoneos CONFIG+=device CONFIG+=qtquickcompiler QMAKE_MAC_XCODE_SETTINGS+=qteam qteam.name=DEVELOPMENT_TEAM qteam.value=6Q32B3V4PN

qmake_all: FORCE

